# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190212_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Not set', max_length=250),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='targetpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
